services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kalbas
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data