services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  metabase_postgres:
    image: postgres:latest
    container_name: postgres_metabase
    ports:
      - "5433:5432" # Exposing a different port for Metabase PostgreSQL
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
      POSTGRES_DB: metabase_db
    volumes:
      - ./metabase_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres_metabase
    depends_on:
      - metabase_postgres
