spring:
  application:
    name: kalbas_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/kalbas
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: mahdi
      password: mahdi


